media:
  input: media
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: cover, label: cover, type: image }
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string }
      - { name: body, label: Body, type: rich-text }
      - { name: description, label: Description, type: string }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
  - name: read_me
    label: ReadMe
    type: file
    path: README.md
    fields:
      - name: body
        label: Body
        type: rich-text