name: Generate Directory JSON

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        
      - name: Create docs directory if it doesn't exist
        run: mkdir -p docs
        
      - name: Generate directory structure JSON
        run: node scanRepo.js
        
       # Commit and push the changes to the repository
      - name: Commit directory structure JSON
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add docs/directory_structure.json
          git commit -m "Update directory structure JSON"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
