name: Sync CMS to Frontend

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch of the CMS repo

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the CMS repository
    - name: Checkout CMS repo
      uses: actions/checkout@v2
      with:
        repository: DORKINHORKIN/cms  # Replace with the correct owner/repo for your CMS repo
        path: cms  # Clone the CMS repo into a 'cms' folder

    # Step 2: Checkout the Frontend (largerest) repository
    - name: Checkout Frontend repo
      uses: actions/checkout@v2
      with:
        repository: DORKINHORKIN/largerest  # Your frontend repo
        path: .  # Checkout frontend repo in the current directory (root)

    # Step 3: Ensure 'cms' folder exists in the frontend repo
    - name: Ensure CMS folder exists in Frontend repo
      run: |
        mkdir -p ./cms  # Create 'cms' folder if it doesn't exist

    # Step 4: Clear the existing 'cms' folder (optional)
    - name: Clear existing CMS content in frontend
      run: |
        rm -rf ./cms/* || true  # Clear 'cms' folder content if it exists, continue if it's already empty

    # Step 5: Copy CMS content into the 'cms' folder in the root of the Frontend repo
    - name: Copy CMS content to Frontend's root 'cms' folder
      run: |
        cp -R cms/* ./cms/ || echo "No files to copy from CMS repo"  # Copy content, or print a message if no files exist

    # Step 6: Commit and Push changes to the Frontend repository
    - name: Commit and Push changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add .
        git commit -m "Sync CMS content from cms repo"
        git push
